### ISSUE TITLE
Issue with Comments 

### ISSUE THREAD

**Issue by Hifive127** [L1fescape/wordpress-showhide#4]
Hey. 

I use your plugin on all my posts, so it's very important for me that it works. However, i stumbled across one issue and i can't figure out whats causing it or how to solve it.  

To get to the point: 
When someone comments on one of my articles your plugin doesn't work, you can see it live here: http://tellingbeatzz.net/when-i-was-up-instrumental/

This only happens if there's a comment, if there's no comment it works like a charme. example: http://tellingbeatzz.net/the-lesson-instrumental/ 

can you help me somehow?

**Comment by L1fescape** [comment]
Sorry for the delayed response. In the middle of moving to San Francisco. I'll check this out when I get a chance, most likely this weekend at the earliest. Sorry again!

**Comment by Hifive127** [comment]
Hey. 

did you have any chance to take a look at it?

**Comment by L1fescape** [comment]
Hey @Hifive127 I think I've fixed the issue. Update to v0.4. Let me know if the issue persists or if there are any more bugs. Sorry again for the delay.

**Comment by Hifive127** [comment]
Thank you!!
